// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartGuardHub.Infrastructure;

#nullable disable

namespace SmartGuardHub.Migrations.SmartGuardDb
{
    [DbContext(typeof(SmartGuardDbContext))]
    [Migration("20260519000000_RenameReadingColumns")]
    partial class RenameReadingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SmartGuardHub.Features.DeviceManagement.DeviceConfigRecord", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ConfigType")
                    .HasColumnType("INTEGER");

                b.Property<Guid>("ConfigVersion")
                    .HasColumnType("TEXT");

                b.Property<string>("Config")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("SyncedToCloud")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("TimeToSyncedToCloud")
                    .HasColumnType("TEXT");

                b.Property<int>("UpdatedFrom")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("UpdateTime")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ConfigType")
                    .IsUnique();

                b.HasIndex("SyncedToCloud");

                b.ToTable("DeviceConfigs");
            });

            modelBuilder.Entity("SmartGuardHub.Features.DeviceManagement.SensorReadingRecord", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsOnline")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("LogTime")
                    .HasColumnType("TEXT");

                b.Property<string>("Reading")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("ReadingTime")
                    .HasColumnType("TEXT");

                b.Property<string>("SensorId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("SyncedToCloud")
                    .HasColumnType("INTEGER");

                b.Property<string>("UnitId")
                    .IsRequired()
                    .HasColumnType("TEXT");


                b.HasKey("Id");

                b.HasIndex("SensorId");

                b.HasIndex("SyncedToCloud");

                b.HasIndex("SensorId", "LogTime");

                b.ToTable("SensorReadings");
            });
#pragma warning restore 612, 618
        }
    }
}
